apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s0j4gzorf-go 
  janus-idp.io/tekton: s0j4gzorf-go
  backstage.io/kubernetes-id: s0j4gzorf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s0j4gzorf-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  