apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: s0j4gzorf-go
  janus-idp.io/tekton: s0j4gzorf-go
  backstage.io/kubernetes-id: s0j4gzorf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s0j4gzorf-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
